version: '3.8'

services:
  web:
    build: .
    command: gunicorn share.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/staticfiles:/usr/src/app/staticfiles
      - /usr/src/app/media:/usr/src/app/media
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ntub_project_share_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - /usr/src/app/staticfiles:/usr/src/app/staticfiles
      - /usr/src/app/media:/usr/src/app/media
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  postgres_data: